FROM ubuntu:latest

LABEL io.k8s.description="control-plane.io base image" \
      io.k8s.display-name="ControlPlane Base"

ENV GOSS_VERSION="v0.3.6"

RUN adduser -h /home/user -s /bin/sh -D user

WORKDIR /home/user

USER root

# TODO: APK del curl from this image
RUN \
  DEBIAN_FRONTEND=noninteractive \
    apt update && apt install --assume-yes --no-install-recommends \
      ca-certificates \
  \
  && rm -rf /var/lib/apt/lists/*

USER user
